FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY ecosystem.config.js ./

RUN npm install
RUN npm install -g pm2

COPY ./dist .

EXPOSE 5000
EXPOSE 443
EXPOSE 80

CMD ["pm2-runtime", "start", "ecosystem.config.js"]